# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/PowerShell/PowerShell/blob/master/docs/building/windows-core.md
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Cortana (Removal)
        allowPrerelease: true
      settings:
        id: "9NFFX4SZZ23L"
        source: msstore
        ensure: absent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: News (Removal)
        allowPrerelease: true
      settings:
        id: "9WZDNCRFHV"
        source: msstore
        ensure: absent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Microsoft News (Removal)
        allowPrerelease: true
      settings:
        id: "9WZDNCRFHVFW"
        source: msstore
        ensure: absent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: News CLI (Removal)
        allowPrerelease: true
      settings:
        id: Atticus64.news
        source: winget
        ensure: absent                
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: News & Weather (Removal)
        allowPrerelease: true
      settings:
        id: "9WZDNCRFJ3Q2"
        source: msstore
        ensure: absent            
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Movies & TV (Removal)
        allowPrerelease: true
      settings:
        id: "9WZDNCRFJ3P2"
        source: msstore
        ensure: absent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Skype (Removal)
        allowPrerelease: true
      settings:
        id: "9WZDNCRFJ364"
        source: msstore
        ensure: absent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Xbox Accessories (Removal)
        allowPrerelease: true
      settings:
        id: "9NBLGGH30XJ3"
        source: msstore
        ensure: absent       
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Hardwood Solitaire Hub (Removal)
        allowPrerelease: true
      settings:
        id: "9NBLGGH4T2XD"
        source: msstore
        ensure: absent 
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Triangle Peg Solitaire (Removal)
        allowPrerelease: true
      settings:
        id: "9P5JVF7M3CTR"
        source: msstore
        ensure: absent 
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Spotify (Removal)
        allowPrerelease: true
      settings:
        id: Spotify.Spotify
        source: 
        ensure: absent                 
  configurationVersion: 0.2.0